CREATE TABLE genre
(
	id INT PRIMARY KEY IDENTITY(1,1),
	genre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE movie
(
	id INT PRIMARY KEY IDENTITY(1,1),
	title VARCHAR(100) UNIQUE,
	release_year INT,
	duration INT,
	rating VARCHAR(5)
);

CREATE TABLE movieGenre
(
	genreId INT FOREIGN KEY REFERENCES genre(id) ON DELETE CASCADE,
	movieId INT FOREIGN KEY REFERENCES movie(id) ON DELETE CASCADE	
);

CREATE TABLE director
(
	id INT PRIMARY KEY IDENTITY(1,1),
	name VARCHAR(300),
	UNIQUE(name)
);

CREATE TABLE directMovie
(
	directorId INT FOREIGN KEY REFERENCES director(id) ON DELETE CASCADE,
	movieId INT FOREIGN KEY REFERENCES movie(id) ON DELETE CASCADE
);

CREATE TABLE actor
(
	id INT PRIMARY KEY IDENTITY(1,1),
	name VARCHAR(300),
	UNIQUE(name)
);

CREATE TABLE actorRole
(
	actorId INT FOREIGN KEY REFERENCES actor(id) ON DELETE CASCADE,
	movieId INT FOREIGN KEY REFERENCES movie(id) ON DELETE CASCADE,
	actor_role VARCHAR(300)
);